stages:
    - test

lint:
    stage: test
    image: $PHP_IMAGE:latest
    before_script:
        - composer update --no-interaction --ansi --prefer-dist
    script:
        - vendor/bin/phing lint
    parallel:
        matrix:
            -
                PHP_IMAGE:
                    - registry.gitlab.com/apploud/images/php/8.0-bin
                    - registry.gitlab.com/apploud/images/php/8.3-bin

requirements:
    stage: test
    image: $PHP_IMAGE:latest
    before_script:
        - composer global require maglnet/composer-require-checker
        - composer update --no-interaction --ansi --prefer-dist
    script:
        - vendor/bin/phing reqs
    parallel:
        matrix:
            -
                PHP_IMAGE:
                    - registry.gitlab.com/apploud/images/php/8.0-bin
                    - registry.gitlab.com/apploud/images/php/8.1-bin
                    - registry.gitlab.com/apploud/images/php/8.2-bin
                    - registry.gitlab.com/apploud/images/php/8.3-bin
                COMPOSER_ARGS:
                    - ''
                    - '--prefer-lowest'

phpstan:
    stage: test
    image: $PHP_IMAGE:latest
    before_script:
        - composer update --no-interaction --ansi --prefer-dist $COMPOSER_ARGS
    script:
        - vendor/bin/phing stan
    parallel:
        matrix:
            -
                PHP_IMAGE:
                    - registry.gitlab.com/apploud/images/php/8.0-bin
                    - registry.gitlab.com/apploud/images/php/8.1-bin
                    - registry.gitlab.com/apploud/images/php/8.2-bin
                    - registry.gitlab.com/apploud/images/php/8.3-bin
                COMPOSER_ARGS:
                    - ''
                    - '--prefer-lowest'

sniffer:
    stage: test
    image: registry.gitlab.com/apploud/images/php/8.3-bin:latest
    before_script:
        - composer update --no-interaction --ansi --prefer-dist $COMPOSER_ARGS
    script:
        - vendor/bin/phing sniffer

tests:
    stage: test
    image: $PHP_IMAGE:latest
    before_script:
        - composer update --no-interaction --ansi --prefer-dist $COMPOSER_ARGS
    script:
        - vendor/bin/phing tests
    parallel:
        matrix:
            -
                PHP_IMAGE:
                    - registry.gitlab.com/apploud/images/php/8.0-bin
                    - registry.gitlab.com/apploud/images/php/8.1-bin
                    - registry.gitlab.com/apploud/images/php/8.2-bin
                    - registry.gitlab.com/apploud/images/php/8.3-bin
                COMPOSER_ARGS:
                    - ''
                    - '--prefer-lowest'
    artifacts:
        paths:
            - log/
        expire_in: 48h
        when: on_failure
